### ISSUE TITLE
Proper way of reopening a window in the same position

### ISSUE THREAD

**Issue by trumank** [SamsDRGMods/DRGLib#60]
I can bind to the window's close even and store the position it was in, but I have to account for the alignment myself and I'm not sure if the properties are intended to be accessible in the first place.

Would it make sense for windows to be reusable? Then there would be no need to recreate them, and they would also be able to remember their own position.

![image](https://user-images.githubusercontent.com/1144160/209612469-7e376e76-6a2d-4c9d-9dae-20f34fe626c8.png)

**Comment by samamstar** [comment]
Added extra parameters to "OnClosed" dispatcher for this purpose. Re-use of windows would require a retooling of the full system, and I don't really see a benefit so this will be fine

**Comment by samamstar** [comment]
Frick my solution to this crashes with older mods.

**Comment by samamstar** [comment]
Guess I'm not editing "OnClosed". Will be a distinct function that you can call yourself instead

**Comment by samamstar** [comment]
Oh great now it's crashing even when I've reverted my changes to OnClosed. Simple add, I thought...

**Comment by samamstar** [comment]
HUH! I guess editing the default value of a variable in a function library was my issue.

**Comment by samamstar** [comment]
Yeah it was. Not to self; don't edit the default value of a function or it won't be backwards-compatible to add that variable

**Comment by samamstar** [comment]
Closed by b78d5e5e15d30f72b0372c69b01c09c5ec7a41fe
