### ISSUE TITLE
Improve out of bounds window handling

### ISSUE THREAD

**Issue by trumank** [SamsDRGMods/DRGLib#61]
Currently it is possible to drag windows out of bounds, but upon drag release, they will snap back into bounds. If windows aren't allowed to go out of bounds, they should be prevented from being dragged out of bounds even temporarily.

I also find it desirable to move windows partially out of bounds so making the bounds check configurable would be nice.

![Screenshot from 2022-12-26 22-55-00](https://user-images.githubusercontent.com/1144160/209613567-1f894093-c6df-469e-8b75-ea72ebae97c4.png)

**Comment by samamstar** [comment]
Implemented by https://github.com/SamsDRGMods/DRGLib/commit/799eca1514a5fd938d0f263b5c77cb725b46d4fa
