### ISSUE TITLE
Memory access violation with latest update (season 3 patch 11)

### ISSUE THREAD

**Issue by SirBlockles** [SamsDRGMods/DRGLib#65]
this mod, and by extension all mods that depend on it, crashes the client with a memory access violation when reloading the spacerig or closing the game. lots of people are reporting this on the modio page, but i'm also posting it here because someone is more likely to have notifications for this than the modio page.

**Comment by samamstar** [comment]
Do you have any reproduction steps? I have been unable to reproduce this bug.

**Comment by SirBlockles** [comment]
I'm not able to reproduce it anymore, but there also have been some silent minor patches to DRG since this report, and since the update was focused on modding, it possibly got quietly fixed.
