### ISSUE TITLE
What happaned to the ModHud?

### ISSUE THREAD

**Issue by igromanru** [SamsDRGMods/DRGLib#74]
Hello, I'm trying to update a mod, but the ModHud repo is gone?
Is it private now or deleted?  
What is the solution?

**Comment by samamstar** [comment]
This is not the correct place for this discussion, being an unrelated mod.

That said, Goldblade has moved the source to a repo he has ownership of (The one I posted was wildly outdated anyways). You can find a link in the DRGModding discord
